---               
- name: test in memory inventory
  hosts: localhost
  connection: local
  become: false   
  gather_facts: false
  tasks:          
                  
    - name: Fetch Instance Info
      os_server_info:
        cloud: openstack
        region_name: regionOne
      register: r_os_servers
                  
    - name: Add host
      add_host:   
        name: "{{ item.public_v4 }}"
        group:    
          - "{{ item.metadata.group }}"
          - "{{ item.metadata.deployment_name }}"
      loop: "{{ r_os_servers.openstack_servers }}"

- name: add repos to provisioned environment
  hosts: all:!localhost
  gather_facts: true
  become: true
  vars:
    repo_files:
      - src: base_repos 
        dest: base_repos.repo
      - src: database_repos
        dest: database_repos.repo
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "/etc/yum.repos.d/{{ item.dest }}" 
        owner: root
        group: root
        mode: '0644'
      loop: "{{ repo_files }}"

    - name: add IP for db to hosts file for app1
      lineinfile:
        path: /etc/hosts
        insertafter: EOF
        line: "{{ groups['database_servers'] }} appdb1"
      when: ansible_hostname == 'app1' or ansible_hostname == 'app2'

